// Auth
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const SIGNUP_SCREEN = 'SIGNUP_SCREEN';
export const SPLASH_SCREEN = 'SPLASH_SCREEN';

// App
export const HOME_SCREEN = 'HOME_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const SETTING_SCREEN = 'SETTING_SCREEN';
export const POSTS_SCREEN = 'POSTS_SCREEN';
export const SEARCH_SCREEN = 'SEARCH_SCREEN';
export const SEARCH_DETAILS_SCREEN = 'SEARCH_DETAILS_SCREEN';
